# Generated by Django 5.2.7 on 2026-03-14 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.FloatField(help_text='Beats per minute (BPM)')),
                ('blood_pressure_sys', models.FloatField(help_text='Systolic BP (mmHg)')),
                ('blood_pressure_dia', models.FloatField(help_text='Diastolic BP (mmHg)')),
                ('spo2', models.FloatField(help_text='Oxygen Saturation (%)')),
                ('bmi', models.FloatField(help_text='Body Mass Index')),
                ('temperature', models.FloatField(help_text='Body Temperature (°C)')),
                ('glucose', models.FloatField(help_text='Blood Glucose (mg/dL)')),
                ('symptoms', models.TextField(blank=True, help_text='Describe any symptoms')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], max_length=10)),
                ('confidence', models.FloatField(default=0.0)),
                ('details', models.TextField()),
                ('specialist_needed', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('health_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='health.healthrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='health.prediction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
