# Generated by Django 5.2.7 on 2026-03-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('specialization', models.CharField(choices=[('General Physician', 'General Physician'), ('Cardiologist', 'Cardiologist'), ('Pulmonologist', 'Pulmonologist'), ('Endocrinologist', 'Endocrinologist'), ('Neurologist', 'Neurologist'), ('Orthopedist', 'Orthopedist'), ('Dermatologist', 'Dermatologist'), ('Gastroenterologist', 'Gastroenterologist'), ('Nephrologist', 'Nephrologist'), ('Psychiatrist', 'Psychiatrist')], max_length=100)),
                ('hospital_name', models.CharField(max_length=200)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('city', models.CharField(default='', max_length=100)),
                ('rating', models.FloatField(default=4.0)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=500.0, max_digits=8)),
                ('is_available', models.BooleanField(default=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
